[project]
name = "rag"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Muhammad Junaid Raza", email = "junaidnaveed030000@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "chromadb>=1.5.9",
    "faiss-cpu>=1.15.1",
    "fonttools>=4.65.0",
    "ipykernel>=7.3.0",
    "langchain>=1.4.2",
    "langchain-community>=0.4.2",
    "langchain-core>=1.6.4",
    "pypdf>=6.19.0",
    "sentence-transformers>=6.1.0",
]

[project.scripts]
rag = "rag:main"

[build-system]
requires = ["uv_build>=0.12.17,<0.13.0"]
build-backend = "uv_build"
